"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-06-19 21:17:20.344890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("active_leaf_message_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_sessions_user_id"),
        "chat_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "chat_session_shares",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("source_session_id", sa.String(length=32), nullable=False),
        sa.Column("source_active_leaf_message_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_session_shares_owner_user_id"),
        "chat_session_shares",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_session_shares_source_session_id"),
        "chat_session_shares",
        ["source_session_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("parent_message_id", sa.Integer(), nullable=True),
        sa.Column("source_message_id", sa.Integer(), nullable=True),
        sa.Column("version_index", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model_id", sa.String(length=120), nullable=True),
        sa.Column("thinking_effort", sa.String(length=80), nullable=True),
        sa.Column("tool_calls_json", sa.Text(), nullable=True),
        sa.Column("parts_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_parent_message_id"),
        "chat_messages",
        ["parent_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"),
        "chat_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_source_message_id"),
        "chat_messages",
        ["source_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_user_id"),
        "chat_messages",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "chat_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_message_id", sa.Integer(), nullable=False),
        sa.Column("assistant_message_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("model_id", sa.String(length=120), nullable=True),
        sa.Column("thinking_effort", sa.String(length=80), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_runs_assistant_message_id"),
        "chat_runs",
        ["assistant_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_runs_session_id"),
        "chat_runs",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_runs_user_id"),
        "chat_runs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_runs_user_message_id"),
        "chat_runs",
        ["user_message_id"],
        unique=False,
    )
    op.create_table(
        "chat_run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=80), nullable=False),
        sa.Column("data_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "sequence",
            name="uq_chat_run_events_run_sequence",
        ),
    )
    op.create_index(
        op.f("ix_chat_run_events_run_id"),
        "chat_run_events",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_run_events_session_id"),
        "chat_run_events",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_run_events_user_id"),
        "chat_run_events",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "chat_context_compressions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("head_end_message_id", sa.Integer(), nullable=False),
        sa.Column("tail_start_message_id", sa.Integer(), nullable=False),
        sa.Column("source_leaf_message_id", sa.Integer(), nullable=False),
        sa.Column("previous_compression_id", sa.Integer(), nullable=True),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("summary_model_id", sa.String(length=120), nullable=True),
        sa.Column("original_token_estimate", sa.Integer(), nullable=False),
        sa.Column("summary_token_estimate", sa.Integer(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_context_compressions_head_end_message_id"),
        "chat_context_compressions",
        ["head_end_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_context_compressions_session_id"),
        "chat_context_compressions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_context_compressions_source_leaf_message_id"),
        "chat_context_compressions",
        ["source_leaf_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_context_compressions_tail_start_message_id"),
        "chat_context_compressions",
        ["tail_start_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_context_compressions_user_id"),
        "chat_context_compressions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "example_async_task_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_example_async_task_logs_task_id"),
        "example_async_task_logs",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "example_async_tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("processed_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("fail_every", sa.Integer(), nullable=False),
        sa.Column("delay_ms", sa.Integer(), nullable=False),
        sa.Column("last_message", sa.Text(), nullable=True),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "example_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "token_usage_audits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("request_index", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model_id", sa.String(length=120), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("tool_tokens", sa.Integer(), nullable=False),
        sa.Column("raw_usage_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "request_index", name="uq_token_usage_run_request"),
    )
    op.create_index(
        op.f("ix_token_usage_audits_created_at"),
        "token_usage_audits",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_usage_audits_model_id"),
        "token_usage_audits",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_usage_audits_provider"),
        "token_usage_audits",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_usage_audits_run_id"),
        "token_usage_audits",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_usage_audits_session_id"),
        "token_usage_audits",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_token_usage_audits_user_id"),
        "token_usage_audits",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "external_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("implementation", sa.String(length=20), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("settings_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "managed_scopes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column(
            "category",
            sa.Enum("NORMAL", "SENSITIVE", "DANGEROUS", name="scopecategory"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope"),
    )
    op.create_table(
        "oauth_provider_authorization_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("code_challenge", sa.String(length=128), nullable=False),
        sa.Column("code_challenge_method", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_provider_authorization_codes_client_id"),
        "oauth_provider_authorization_codes",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_provider_authorization_codes_code_hash"),
        "oauth_provider_authorization_codes",
        ["code_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_provider_authorization_codes_user_id"),
        "oauth_provider_authorization_codes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "oauth_provider_clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=80), nullable=False),
        sa.Column("client_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("redirect_uris", sa.Text(), nullable=False),
        sa.Column("allowed_scopes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("require_pkce", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_provider_clients_client_id"),
        "oauth_provider_clients",
        ["client_id"],
        unique=True,
    )
    op.create_table(
        "oauth_provider_device_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_code_hash", sa.String(length=64), nullable=False),
        sa.Column("user_code_hash", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_provider_device_codes_client_id"),
        "oauth_provider_device_codes",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_provider_device_codes_device_code_hash"),
        "oauth_provider_device_codes",
        ["device_code_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_provider_device_codes_user_code_hash"),
        "oauth_provider_device_codes",
        ["user_code_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_provider_device_codes_user_id"),
        "oauth_provider_device_codes",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "oauth_provider_refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.String(length=80), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_provider_refresh_tokens_client_id"),
        "oauth_provider_refresh_tokens",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_oauth_provider_refresh_tokens_token_hash"),
        "oauth_provider_refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_provider_refresh_tokens_user_id"),
        "oauth_provider_refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("scope_overrides", sa.Text(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "INACTIVE", name="userstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=False),
        sa.Column("two_factor_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("two_factor_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "login_challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_jti", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_challenges_challenge_jti"),
        "login_challenges",
        ["challenge_jti"],
        unique=True,
    )
    op.create_index(
        op.f("ix_login_challenges_user_id"),
        "login_challenges",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_user_id", sa.String(length=120), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider_username", sa.String(length=120), nullable=True),
        sa.Column("provider_email", sa.String(length=255), nullable=True),
        sa.Column("provider_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_user_id", name="uq_oauth_provider_user"
        ),
        sa.UniqueConstraint("provider", "user_id", name="uq_oauth_provider_local_user"),
    )
    op.create_index(
        op.f("ix_oauth_accounts_provider"), "oauth_accounts", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "oauth_login_tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticket_hash", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("challenge_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_login_tickets_ticket_hash"),
        "oauth_login_tickets",
        ["ticket_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_oauth_login_tickets_user_id"),
        "oauth_login_tickets",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "user_backup_codes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_backup_codes_user_id"),
        "user_backup_codes",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_context_compressions_user_id"),
        table_name="chat_context_compressions",
    )
    op.drop_index(
        op.f("ix_chat_context_compressions_tail_start_message_id"),
        table_name="chat_context_compressions",
    )
    op.drop_index(
        op.f("ix_chat_context_compressions_source_leaf_message_id"),
        table_name="chat_context_compressions",
    )
    op.drop_index(
        op.f("ix_chat_context_compressions_session_id"),
        table_name="chat_context_compressions",
    )
    op.drop_index(
        op.f("ix_chat_context_compressions_head_end_message_id"),
        table_name="chat_context_compressions",
    )
    op.drop_table("chat_context_compressions")
    op.drop_index(op.f("ix_chat_run_events_user_id"), table_name="chat_run_events")
    op.drop_index(op.f("ix_chat_run_events_session_id"), table_name="chat_run_events")
    op.drop_index(op.f("ix_chat_run_events_run_id"), table_name="chat_run_events")
    op.drop_table("chat_run_events")
    op.drop_index(op.f("ix_chat_runs_user_message_id"), table_name="chat_runs")
    op.drop_index(op.f("ix_chat_runs_user_id"), table_name="chat_runs")
    op.drop_index(op.f("ix_chat_runs_session_id"), table_name="chat_runs")
    op.drop_index(op.f("ix_chat_runs_assistant_message_id"), table_name="chat_runs")
    op.drop_table("chat_runs")
    op.drop_index(op.f("ix_chat_messages_user_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_source_message_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_parent_message_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(
        op.f("ix_chat_session_shares_source_session_id"),
        table_name="chat_session_shares",
    )
    op.drop_index(
        op.f("ix_chat_session_shares_owner_user_id"),
        table_name="chat_session_shares",
    )
    op.drop_table("chat_session_shares")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_user_backup_codes_user_id"), table_name="user_backup_codes")
    op.drop_table("user_backup_codes")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        op.f("ix_oauth_login_tickets_user_id"), table_name="oauth_login_tickets"
    )
    op.drop_index(
        op.f("ix_oauth_login_tickets_ticket_hash"), table_name="oauth_login_tickets"
    )
    op.drop_table("oauth_login_tickets")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_index(op.f("ix_oauth_accounts_provider"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index(op.f("ix_login_challenges_user_id"), table_name="login_challenges")
    op.drop_index(
        op.f("ix_login_challenges_challenge_jti"), table_name="login_challenges"
    )
    op.drop_table("login_challenges")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_oauth_provider_refresh_tokens_user_id"),
        table_name="oauth_provider_refresh_tokens",
    )
    op.drop_index(
        op.f("ix_oauth_provider_refresh_tokens_token_hash"),
        table_name="oauth_provider_refresh_tokens",
    )
    op.drop_index(
        op.f("ix_oauth_provider_refresh_tokens_client_id"),
        table_name="oauth_provider_refresh_tokens",
    )
    op.drop_table("oauth_provider_refresh_tokens")
    op.drop_index(
        op.f("ix_oauth_provider_device_codes_user_id"),
        table_name="oauth_provider_device_codes",
    )
    op.drop_index(
        op.f("ix_oauth_provider_device_codes_user_code_hash"),
        table_name="oauth_provider_device_codes",
    )
    op.drop_index(
        op.f("ix_oauth_provider_device_codes_device_code_hash"),
        table_name="oauth_provider_device_codes",
    )
    op.drop_index(
        op.f("ix_oauth_provider_device_codes_client_id"),
        table_name="oauth_provider_device_codes",
    )
    op.drop_table("oauth_provider_device_codes")
    op.drop_index(
        op.f("ix_oauth_provider_clients_client_id"), table_name="oauth_provider_clients"
    )
    op.drop_table("oauth_provider_clients")
    op.drop_index(
        op.f("ix_oauth_provider_authorization_codes_user_id"),
        table_name="oauth_provider_authorization_codes",
    )
    op.drop_index(
        op.f("ix_oauth_provider_authorization_codes_code_hash"),
        table_name="oauth_provider_authorization_codes",
    )
    op.drop_index(
        op.f("ix_oauth_provider_authorization_codes_client_id"),
        table_name="oauth_provider_authorization_codes",
    )
    op.drop_table("oauth_provider_authorization_codes")
    op.drop_table("managed_scopes")
    op.drop_table("external_providers")
    op.drop_index(op.f("ix_token_usage_audits_user_id"), table_name="token_usage_audits")
    op.drop_index(
        op.f("ix_token_usage_audits_session_id"),
        table_name="token_usage_audits",
    )
    op.drop_index(op.f("ix_token_usage_audits_run_id"), table_name="token_usage_audits")
    op.drop_index(
        op.f("ix_token_usage_audits_provider"),
        table_name="token_usage_audits",
    )
    op.drop_index(
        op.f("ix_token_usage_audits_model_id"),
        table_name="token_usage_audits",
    )
    op.drop_index(
        op.f("ix_token_usage_audits_created_at"),
        table_name="token_usage_audits",
    )
    op.drop_table("token_usage_audits")
    op.drop_table("example_items")
    op.drop_table("example_async_tasks")
    op.drop_index(
        op.f("ix_example_async_task_logs_task_id"), table_name="example_async_task_logs"
    )
    op.drop_table("example_async_task_logs")
    # ### end Alembic commands ###
